### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by youngqqcn** [HuobiGroup/huobi-eco-chain#69]
```
INFO [08-19|19:24:41.001] Successfully sealed new block            number=200 sealhash=3b2230..f94e91 hash=c9f983..6611fc elapsed=2.996s
INFO [08-19|19:24:41.001] 🔗 block reached canonical chain          number=193 hash=bcde61..ad91c3
INFO [08-19|19:24:41.001] 🔨 mined potential block                  number=200 hash=c9f983..6611fc
panic: runtime error: integer divide by zero

goroutine 72 [running]:
github.com/ethereum/go-ethereum/consensus/congress.(*Snapshot).inturn(0x0?, 0xc9, {0xb4, 0x5b, 0x3b, 0x1a, 0xa3, 0x53, 0x24, 0x77, ...})
        github.com/ethereum/go-ethereum/consensus/congress/snapshot.go:203 +0xb0
github.com/ethereum/go-ethereum/consensus/congress.calcDifficulty(0xa39de29dcec6bd7f?, {0xb4, 0x5b, 0x3b, 0x1a, 0xa3, 0x53, 0x24, 0x77, 0xd8, ...})
        github.com/ethereum/go-ethereum/consensus/congress/congress.go:1119 +0x4c
github.com/ethereum/go-ethereum/consensus/congress.(*Congress).Prepare(0xc0002e75f0, {0x17dc278, 0xc00060b000}, 0xc002f22900)
        github.com/ethereum/go-ethereum/consensus/congress/congress.go:571 +0x127
github.com/ethereum/go-ethereum/miner.(*worker).commitNewWork(0xc000142000, 0xc00025bc94?, 0x0, 0x62ff72f9)
        github.com/ethereum/go-ethereum/miner/worker.go:956 +0x645
github.com/ethereum/go-ethereum/miner.(*worker).mainLoop(0xc000142000)
        github.com/ethereum/go-ethereum/miner/worker.go:474 +0x63b
created by github.com/ethereum/go-ethereum/miner.newWorker
        github.com/ethereum/go-ethereum/miner/worker.go:241 +0x78a
make: *** [Makefile:8：start] 错误 2
```

**Comment by youngqqcn** [comment]
https://github.com/stars-labs/heco-chain/blob/123ccb14caf0bb27a7563de7f55db54910d92fdd/consensus/congress/snapshot.go#L196-L203


`s.validators()` 什么时候会为空？

**Comment by ken0x4b656e** [comment]
If you're running a private chain, you need to set your genesis file correctly, with some necessary system-contracts, refer to  <https://docs.hecochain.com/#/dev/private_chain> for details.

**Comment by dfgdfger** [comment]
ITS IN THE TANSACTION LOGS 
Transaktionsdaten
{
    "chainId": 128,
    "from": "0x7e5f4552091a69125d5dfcb7b8c2659029395bdf",
    "to": "0xa615fa212b1d7d195060bacf0d523a952c119ca6",
    "value": "0x" <---- INTEGER
}
